# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/home/victor/work/piff/webdav-client-cpp;/home/victor/work/piff/webdav-client-cpp")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libssl-dev (>= 1.0.1f), libcurl4-openssl-dev (>= 7.38.0), libpugixml-dev (>= 1.0.0)")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://designerror.github.io/webdav-client-cpp")
set(CPACK_DEBIAN_PACKAGE_NAME "libwdc-dev")
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.1")
set(CPACK_DEBIAN_PACKAGE_RELEASE "1")
set(CPACK_GENERATOR "STGZ;TGZ;TZ")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/victor/work/piff/webdav-client-cpp;WDC;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "WDC 1.1.5")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "WDC 1.1.5")
set(CPACK_OUTPUT_CONFIG_FILE "/home/victor/work/piff/webdav-client-cpp/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "designerror@yandex.ru")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/victor/work/piff/webdav-client-cpp/DESCRIPTION")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "C++ WebDAV Client library")
set(CPACK_PACKAGE_FILE_NAME "WDC-1.1.5-Linux")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "WDC 1.1.5")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "WDC 1.1.5")
set(CPACK_PACKAGE_NAME "WDC")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "1.1.5")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "5")
set(CPACK_PROJECT_CONFIG_FILE "/home/victor/work/piff/webdav-client-cpp/cmake/Package.cmake.in")
set(CPACK_RESOURCE_FILE_LICENSE "/home/victor/work/piff/webdav-client-cpp/LICENSE")
set(CPACK_RESOURCE_FILE_README "/home/victor/work/piff/webdav-client-cpp/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.13/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_CHANGELOG_FILE "/home/victor/work/piff/webdav-client-cpp/ChangeLog.md")
set(CPACK_RPM_PACKAGE_GROUP "wdc")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_NAME "wdc-devel")
set(CPACK_RPM_PACKAGE_RELEASE "1")
set(CPACK_RPM_PACKAGE_REQUIRES "openssl-devel >= 1.0.1f, curl-devel >= 7.38.0 pugixml-devel >= 1.0.0")
set(CPACK_RPM_PACKAGE_URL "https://github.com/designerror/webdav-client-cpp")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/victor/work/piff/webdav-client-cpp/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/victor/work/piff/webdav-client-cpp/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
